@startuml
'http://plantuml.com/skinparam.html
skinparam monochrome true
skinparam packageStyle rect
skinparam shadowing false


participant buildingRoute  as route
participant buildingController as controller
participant "mapper2:Json2DTO" as jsonMapper
participant "IBuildingDTO1:IBuildingDTO" as dto1
participant "IBuildingDTO1.1:IBuildingDTO" as dto2
participant "IBuildingService1:IBuildingService" as service
participant "building1:Building" as domain
participant "buildingRepo1:IBuildingRepo" as repository
participant "mapper2:Domain2Data" as mapper1
participant "dataX1:DataX" as data
participant "dbDriver1:IDBDriver" as db
participant "x1saved:X" as savedDomain
participant "savedX1:DataX" as savedData



-> route: Post /X / (json)
activate route
  route->controller: createX(json)
  activate controller
    controller -> controller:validate(json)
    activate controller
    deactivate
    controller -> jsonMapper:map2DTOX(json)
    activate jsonMapper
    jsonMapper --> dto1**:create(json)
    deactivate
    controller ->service:createX(dtoX1):dtoX1.1
    activate service
    service--> domain**:create(dtoX1)
    service->repository:save(x1):x1Saved
    activate repository
    repository -> mapper1:map2Data(x1)
    activate mapper1
    mapper1 -> domain:getAttr()
    activate domain
    deactivate
    mapper1 --> data**:create(attr, ...)
    deactivate
    repository -> db:save(dataX1): savedX1
    activate db
    db --> savedData**:create(savedX1)
    deactivate
    repository->mapper1:map2Model(savedX1)
    activate mapper1
    mapper1 --> savedDomain**
    deactivate
    deactivate
    service -> jsonMapper: map2dto(x1saved):dtoX1.1
    deactivate
    activate jsonMapper
    jsonMapper -> savedDomain: getAttr():attr
    activate savedDomain
    deactivate
    jsonMapper --> dto2**:create(attr, ...)
    deactivate
    controller -> jsonMapper:map2Json(dtoX1.1):json
    activate jsonMapper
    deactivate
    controller->controller:generateRes(json)
    controller--> route:response
    deactivate
    <- route:response
    deactivate





@enduml