@startuml
'http://plantuml.com/skinparam.html
skinparam monochrome true
skinparam packageStyle rect
skinparam shadowing false


participant buildingRoute  as route
participant buildingController as controller
participant "mapper2:Json2DTO" as jsonMapper
participant "IBuildingDTO1:IBuildingDTO" as dto1
participant "IBuildingDTO1.1:IBuildingDTO" as dto2
participant "IBuildingService1:IBuildingService" as service
participant "building1:Building" as domain
participant "buildingRepo1:IBuildingRepo" as repository
participant "mapper2:Domain2Data" as mapper1
participant "Building1:BuildingData" as data
participant "dbDriver1:IDBDriver" as db
participant "Building1saved:Building" as savedDomain
participant "Buildingsaved1:BuildingData" as savedData



-> route: Post /buildings / (json)
activate route
  route->controller: createBuilding(json)
  activate controller
    controller -> controller:validate(json)
    controller -> jsonMapper:map2DTO(json)
    activate jsonMapper
    jsonMapper -> dto1**:create(json)
    dto1-->jsonMapper:buildingDTO1
    jsonMapper --> controller:buildingDTO1
    deactivate
    controller ->service:createBuilding(buildingDTO1)
    activate service
    service-> domain**:create(building1)
    domain --> service:building1
    service->repository:save(building1)
    activate repository
    repository -> mapper1:map2Data(building1)
    activate mapper1
    mapper1 -> domain:getCode()
    activate domain
    domain--> mapper1:code
    mapper1 -> domain:getName()
    domain--> mapper1:name
    mapper1 -> domain:getDescription()
    domain--> mapper1:description
    mapper1 -> domain:getDimensions()
    domain--> mapper1:dimensions
    deactivate
    mapper1 -> data**:create(code,name,dimensions,description, ...)
    data --> mapper1:buildingData
    mapper1 --> repository:buildingData
    deactivate
    repository -> db:save(buildingData)
    activate db
    db -> savedData**:create(savedBuilding)
    db --> repository:savedBuilding
    deactivate
    repository->mapper1:map2Model(savedBuilding)
    activate mapper1
    mapper1 -> savedDomain**
    savedDomain --> mapper1:buildingSaved
    mapper1 --> repository:buildingSaved
    repository --> service:buildingSaved
    deactivate
    deactivate
    service -> jsonMapper: map2dto(buildingSaved)
    activate jsonMapper
    jsonMapper -> savedDomain: getName()
    activate savedDomain
    savedDomain --> jsonMapper:name
    jsonMapper -> savedDomain: getCode()
    savedDomain --> jsonMapper:code
    jsonMapper -> savedDomain: getDescription()
    savedDomain --> jsonMapper:description
    jsonMapper -> savedDomain: getDimensions()
    savedDomain --> jsonMapper:dimensions
    deactivate
    jsonMapper --> dto2**:create(name,code,dimensions,description, ...)
    dto2 --> jsonMapper:savedBuildingDTO
    jsonMapper --> service: savedBuildingDTO
    deactivate
    service --> controller:savedBuildingDTO
    deactivate
    controller -> jsonMapper:map2Json(savedBuildingDTO):json
    activate jsonMapper
    jsonMapper --> controller:json
    deactivate
    controller->controller:generateRes(json)
    controller--> route:response
    deactivate
    <- route:response
    deactivate





@enduml